package edu.richmond.adminsys.conduit.monitors

import groovy.util.slurpersupport.GPathResult
import java.text.SimpleDateFormat
import edu.richmond.adminsys.conduit.ICMonitor
import edu.richmond.adminsys.conduit.ICFitting
/**
 * 
 * The ConsoleMonitor publishes events generated by sources or sinks during the transformation to the Console.
 * 
 * @author dbroome
 *
 */
class ConsoleMonitor implements ICMonitor {

    SimpleDateFormat dateFormat

    @Override
    void logEvent(ICFitting generator, Map event) {
        if (event['message'] != null) {
            String when = (dateFormat != null)? dateFormat.format(new Date()) : new Date().toString()
            System.out.println("${when} - ${event['message']}")
        }
    }

    @Override
    void setUp(GPathResult config) {
        if (config.dateFormat != null) {
            dateFormat = new SimpleDateFormat(config.dateFormat.text())
        }
    }

    @Override
    void tearDown() {
        //nothing to do
    }
}
