package edu.richmond.adminsys.conduit
/**
 * The ICMonitor interface is implemented by any classes that will observe the events generated by the source and sink components and display or persist them.
 * 
 * @author dbroome
 *
 */
interface ICMonitor extends ICFitting {
    /**
     * Called by the messagePump object during transformations to distribute events logged by the source and sink objects.
     * 
     * @param generator The object that generated the message.
     * @param event A Map containing key-value pairs about what a source or sink component is doing during a transformation.
     */
	void logEvent(ICFitting generator, Map event)
}
